### ISSUE TITLE
How to prediction on single image

### ISSUE THREAD

**Issue by masudbaki** [moein-shariatnia/Deep-Learning#1]
sir, How to do prediction on single image?

**Comment by moein-shariatnia** [comment]
> sir, How to do prediction on single image?

Hey,
If you are following along the Colab notebook, you can use the following code snippet to do prediction on a single image and visualize the final result. Note that you need to define the model (as noted in the notebook) and load the pretrained weights that I've provided there:

```
img = PIL.Image.open("black_and_white.jpg")
img = img.resize((256, 256))
# to make it between -1 and 1
img = transforms.ToTensor()(img)[:1] * 2. - 1.
model.eval()
with torch.no_grad():
    preds = model.net_G(img.unsqueeze(0).to(device))
plt.imshow(lab_to_rgb(img.unsqueeze(0), preds.cpu())[0])
```

I hope this helps you out. Please let me know if there is any problem. Good Luck!

**Comment by masudbaki** [comment]
also sir if you help me with this error
`AttributeError: Can't get attribute 'MainModel' on <module '__main__'>`
this error happens when i saved the model with `torch.save(model,"fullmodel.pt')`
when i was using the same colab in which i have done the training path, the `torch.load("fullmodel.pt")` worked perfectly.. but in another colab where i uploaded the fullmodel.pt it gives the error `AttributeError: Can't get attribute 'MainModel' on <module '__main__'>` when loading the model with `torch.load("fullmodel.pth")`..

**Comment by masudbaki** [comment]
thanks it worked

**Comment by masudbaki** [comment]
Thank you sir

**Comment by moein-shariatnia** [comment]
Hey, you should be actually saving "model.state_dict()" instead of "model"
itself. I think this would resolve your error.

**Comment by masudbaki** [comment]
Thanks..it works now perfectly...

**Comment by countradooku** [comment]
> > sir, How to do prediction on single image?
> 
> 
> 
> Hey,
> 
> If you are following along the Colab notebook, you can use the following code snippet to do prediction on a single image and visualize the final result. Note that you need to define the model (as noted in the notebook) and load the pretrained weights that I've provided there:
> 
> 
> 
> ```
> 
> img = PIL.Image.open("black_and_white.jpg")
> 
> img = img.resize((256, 256))
> 
> # to make it between -1 and 1
> 
> img = transforms.ToTensor()(img)[:1] * 2. - 1.
> 
> model.eval()
> 
> with torch.no_grad():
> 
>     preds = model.net_G(img.unsqueeze(0).to(device))
> 
> plt.imshow(lab_to_rgb(img.unsqueeze(0), preds.cpu())[0])
> 
> ```
> 
> 
> 
> I hope this helps you out. Please let me know if there is any problem. Good Luck!

Why we transforms it between -1 and 1 and not 0 1

**Comment by moein-shariatnia** [comment]
> Why we transforms it between -1 and 1 and not 0 1
@radudiaconu0 

The model has been trained in this way so the evaluation must be done in the same way. 
The generator architecture contains a Tanh function in the last layer, so, the generated image is between -1 and 1. So, the real images coming to discriminator should be in the same range. That's the reason why we scale between -1 and 1 in the dataset.
