### ISSUE TITLE
can't create the body of ResNet18

### ISSUE THREAD

**Issue by DanielaGrassi** [moein-shariatnia/Deep-Learning#2]
Hi! first of all i have to say thank you for this code, it's a great job!

I was trying this part of the code:

```
from fastai.vision.data import create_body
from fastai.vision import models
from torchvision.models.resnet import resnet18
from fastai.vision.models.unet import DynamicUnet

def build_res_unet(n_input=1, n_output=2, size=256):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    body = create_body(resnet18, n_in = n_input, pretrained=True, cut=-2)
    net_G = DynamicUnet(body, n_output, (size, size)).to(device)
    return net_G

net_G = build_res_unet(n_input=1, n_output=2, size=256) 

```

but I keep getting an error:

`TypeError: create_body() got an unexpected keyword argument 'n_in'`
but in the fastai docs the n_in parameter is present.
How do you think we can resolve?

**Comment by peppocola** [comment]
restart your environment and add `!pip install fastai==2.4` on top. This should work :)

**Comment by moein-shariatnia** [comment]
> Hi! first of all i have to say thank you for this code, it's a great job!
Hi, thanks for your comment. I'm glad you liked it!

> How do you think we can resolve?

Please try what @peppocola suggested (thanks @peppocola !) and let me know if this resolves the issue,
Thank you all.

**Comment by DanielaGrassi** [comment]
Seems to work, thanks to both of you!
