### ISSUE TITLE
The code takes 4h foe each epoch in google colab.

### ISSUE THREAD

**Issue by damorosodaragona** [moein-shariatnia/Deep-Learning#3]
Hi,
i'm trying to run your code but in google colab the time needed for each epoch si about 4h:
![image](https://user-images.githubusercontent.com/15249587/131990436-0172622a-f1f7-4da7-ab62-1fe0add0490c.png)

I also downloaded the notebook and run it on my local machine with cuda and GTX 1050 and the time needed  is about 30min for every epoch. 

Do you have an idea why this happens? It seems should be necessary only 3-4min for every epoch.

EDIT: 
I forgot to change the runtime type to colab, now it takes about 10min, however i cant't understand why on my lapton takes 30-40min.

**Comment by moein-shariatnia** [comment]
Hey @damorosodaragona ,

Good that your problem is resolved; I was just writing you about changing the runtime to GPU that I saw you edited your post.

About the issue regarding your laptop, I should admit that I'm not an expert in GPUs but after a quick looking up your GPU specs vs Tesla K80 which Colab offers, I think it is not that unexpected that it takes too long on your laptop and not on Colab. 
I think K80 GPU is a better fit for deep learning rather than 1050; although I could be totally wrong.

**Comment by damorosodaragona** [comment]
Thaks @moein-shariatnia . 

I have couple of "stupid" question more: 

a) in the colab notebook is written that we are using 8000 images for the training of the model and in the following images 

![image](https://user-images.githubusercontent.com/15249587/132015972-61fcd8f4-b4d2-4db2-965d-eb33cb53a2c4.png)

this is explained very well. 

But if we are using 8000 samples why the train_model function iterates over only 500 images? 

![image](https://user-images.githubusercontent.com/15249587/132016179-d0bd054f-06d7-404b-8181-3b05beafcff2.png)


b) the output that we visualize every 200 iteration is composed by: 
- on the top the b/n images
- in the middle the results of the colorization (so the prediction of the L,b channels of our model)
- at the bottom the real image
it is right? 
I'm asking this because in the visualize function the images in the middle are called "fake_image" and this are getting me in confusion.

![image](https://user-images.githubusercontent.com/15249587/132017058-11027747-54aa-4e18-85f4-440279083413.png)

**Comment by moein-shariatnia** [comment]
It is alright!

a) That number, 500, shows the number of batches. Each batch is composed of 16 images and 16 * 500 will be 8000 which is the number of training images

b) Yes, the interpretation is right. Fake images denote the colored images which the model predicts and real images are the colorful target images that we wish the model learns to predict.
I used the terms fake vs real from the GAN literature which denotes the images predicted by the generator and the real-world data respectively.

I hope this helps.
